from __future__ import annotations

import shutil
import subprocess
import textwrap
from pathlib import Path

from python2binary.interfaces.interfaces import ICompiler
from python2binary.schemas.schemas import Python2BinaryConfig


# ---------------------------------------------------------------------------
# C launcher template
# ---------------------------------------------------------------------------
_LAUNCHER_TEMPLATE = """\
/*
 * Auto-generated by python2binary – do not edit.
 * Embeds a Python .pyz archive and executes it via python3 at runtime.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "{header_filename}"

int main(int argc, char *argv[]) {{
    /* ------------------------------------------------------------------ */
    /* 1. Write the embedded .pyz payload to a temp file                  */
    /* ------------------------------------------------------------------ */
    const char *tmp_path = "/tmp/{app_name}_python2binary.pyz";

    FILE *fp = fopen(tmp_path, "wb");
    if (!fp) {{
        perror("python2binary: failed to open temp file");
        return 1;
    }}
    fwrite(pyz_data, 1, pyz_data_len, fp);
    fclose(fp);
    chmod(tmp_path, 0755);

    /* ------------------------------------------------------------------ */
    /* 2. Build argv for python3 <archive> [original args...]             */
    /* ------------------------------------------------------------------ */
    /* argc + 2: python3, tmp_path, original argv[1..], NULL sentinel     */
    char **new_argv = (char **)malloc((argc + 2) * sizeof(char *));
    if (!new_argv) {{
        perror("python2binary: malloc failed");
        return 1;
    }}

    new_argv[0] = "python3";
    new_argv[1] = (char *)tmp_path;
    for (int i = 1; i < argc; i++) {{
        new_argv[i + 1] = argv[i];
    }}
    new_argv[argc + 1] = NULL;

    /* ------------------------------------------------------------------ */
    /* 3. Replace the current process image with python3                  */
    /* ------------------------------------------------------------------ */
    execvp("python3", new_argv);

    /* execvp only returns on error */
    perror("python2binary: execvp(python3) failed");
    free(new_argv);
    return 1;
}}
"""


class CCompiler(ICompiler):
    """Generates a C launcher embedding the .pyz payload and compiles it.

    The generated binary:
    1. Writes the embedded bytes to ``/tmp/<app_name>_python2binary.pyz`` at startup.
    2. Uses ``execvp`` to replace itself with ``python3 <tmp_pyz> [args...]``.

    This means the binary itself carries no Python interpreter — the host's
    ``python3`` is used, which is intentional since the project targets
    environments where Python is already installed.
    """

    def compile(
        self, hex_header_path: Path, config: Python2BinaryConfig
    ) -> tuple[Path, Path]:
        """Generate C source, compile it, return (c_source_path, binary_path).

        Args:
            hex_header_path: Path to the .h file from XxdConverter.
            config:          Full build configuration.

        Returns:
            Tuple of (path to .c source file, path to compiled binary).

        Raises:
            RuntimeError: If ``gcc`` is unavailable or compilation fails.
        """
        if shutil.which("gcc") is None:
            raise RuntimeError(
                "'gcc' was not found on PATH. "
                "Install build-essential (e.g. 'apt-get install build-essential') and retry."
            )

        if not hex_header_path.is_file():
            raise FileNotFoundError(
                f"hex_header_path does not exist: {hex_header_path}"
            )

        config.output_dir.mkdir(parents=True, exist_ok=True)

        # Generate the C source file
        c_source = _LAUNCHER_TEMPLATE.format(
            header_filename=hex_header_path.name,
            app_name=config.app_name,
        )
        c_path = config.output_dir / f"{config.app_name}_launcher.c"
        c_path.write_text(c_source, encoding="utf-8")

        # Compile with gcc
        binary_path = config.output_dir / config.app_name
        try:
            subprocess.run(
                [
                    "gcc",
                    "-O2",
                    "-o", str(binary_path),
                    str(c_path),
                    f"-I{config.output_dir}",  # so the #include finds the .h
                ],
                capture_output=True,
                text=True,
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(
                f"gcc compilation failed:\n{exc.stderr}"
            ) from exc

        return c_path, binary_path
